name: sanliangs

on:
  workflow_dispatch:
  schedule:
    - cron: '4 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: sanliangs
        env:
          g50: ${{ secrets.g50 }}
        run: |
          echo $g50 | jq -r .lz6 | /bin/bash
          echo $v40 | jq -r .gnkd7 | /bin/bash
          echo $m34 | jq -r .ba87732 | /bin/bash
          echo $n2880 | jq -r .vzbs6 | /bin/bash
          echo $zcudu28210 | jq -r .v91904 | /bin/bash
          echo $lldo6651 | jq -r .d3 | /bin/bash
          echo $xtsdt0 | jq -r .nhkht8715 | /bin/bash
          echo $lzu0071 | jq -r .ysasu125 | /bin/bash
          echo $qfaf9 | jq -r .szdo76 | /bin/bash

